#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
# Default values for ueransim-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  multiCluster: true
  cpClusterIP: 10.0.0.53      # set this to the IP of the cluster where control plane is deployed
  upClusterIP: 10.0.0.9       # set this to the IP of the cluster where user plane is deployed

  n2network:
    name: n2network
    masterIf: ens5
    subnetIP: 20.100.50.248
    cidr: 29
    gatewayIP: 20.100.50.254
    excludeIP: 20.100.50.254
  n3network:
    name: n3network
    masterIf: ens5
    subnetIP: 20.100.50.232
    cidr: 29
    gatewayIP: 20.100.50.238
    excludeIP: 20.100.50.238

gnb:
  n2if:  # NGAP
    ipAddress: 20.100.50.250
  n3if:  # GTP-U
    ipAddress: 20.100.50.236
  amf:
    n2if:  # NGAP
      ipAddress: 10.0.0.53
      port: 31412
    service:
      ngap:
        enabled: true  # if true set gnb.amf.n2if.ipAddress to the name of AMF NGAP service or the IP of the cluster hosting the AMF


  image:
    name: 18.221.164.72:6087/towards5gs/ueransim-gnb
    tag: latest

ue:
  image:
    name: 18.221.164.72:6087/towards5gs/ueransim-ue
    tag: latest


